#!/usr/bin/env sh

set -eu

USER=deployer
TARGET=${1:-testing}

if [[ $TARGET == "production" ]]; then
  SERVER=acceso.miautohoy.com
  APP_PATH=/var/www/miautohoy.com/current
  SERVICE=miautohoy
else
  SERVER=test.miautohoy.com
  APP_PATH=/var/www/test.miautohoy.com/current
  SERVICE=miautohoytest
fi

echo "Deploying to $TARGET, please wait..."

ssh $USER@$SERVER "mkdir -p $APP_PATH"
rsync -az --delete --exclude .git --exclude .gitignore \
  --exclude deploy --exclude node_modules \
  --exclude prod \
  -e ssh . $USER@$SERVER:$APP_PATH
ssh $USER@$SERVER "cd $APP_PATH && ./build.sh"
ssh root@$SERVER "systemctl restart $SERVICE"

echo "Deploy finished"
